[package]
name = "rna_secondary_structure"
version = "0.1.0"
authors = ["Michael Golden <michaelgolden0@gmail.com"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
